version: "3"
services:
  release:
    image: quay.io/energisk/experian-service:${DOCKER_IMAGE_TAG}
    build:
      context: .
      args:
        mavenUser: ${MAVEN_USER}
        mavenPass: ${MAVEN_PASS}
    ports:
      - 8080:8080
    environment:
      EXPERIAN_USERNAME: ${EXPERIAN_USERNAME}
      EXPERIAN_PASSWORD: ${EXPERIAN_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      INSTANCE_BUCKET: ${INSTANCE_BUCKET}
